export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOGGLE_CART_STATE = "TOGGLE_CART_STATE";